services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
volumes:
  db-data: